server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/costmanage?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 20
      minimum-idle: 8
mybatis-plus:
  type-aliases-package: com.cm.pojo
logging:
  level:
    com.cm.mapper: debug